"""delete utc msk

Revision ID: 492f6c4ba82c
Revises: 1daf21910410
Create Date: 2025-07-23 06:36:03.267359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492f6c4ba82c'
down_revision: Union[str, Sequence[str], None] = '1daf21910410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.CHAR(length=1), server_default=sa.text("'N'"), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), server_default=sa.text("'USER'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
